# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wms', '0005_auto_20170404_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_store', models.IntegerField(blank=True, null=True, verbose_name='\u76d8\u70b9\u5e93\u5b58')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.Product', verbose_name='\u5546\u54c1\u7f16\u7801')),
            ],
        ),
    ]
