# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.CharField(max_length=8, verbose_name='\u5e93\u4f4d\u6761\u7801')),
                ('state', models.CharField(choices=[('1', '\u53ef\u7528\u5e93\u4f4d'), ('2', '\u5df2\u7528\u5e93\u4f4d')], max_length=8, verbose_name='\u5e93\u4f4d\u72b6\u6001')),
                ('type', models.CharField(choices=[('1', '\u5e73\u9762\u4ed3'), ('2', '\u7acb\u4f53\u4ed3')], default=1, max_length=8, verbose_name='\u5e93\u4f4d\u7c7b\u578b')),
                ('category', models.CharField(choices=[('1', '\u5168\u529f\u80fd'), ('2', '\u5176\u4ed6')], default=1, max_length=8, verbose_name='\u5e93\u4f4d\u7c7b\u522b')),
                ('freeze_flag', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='N', max_length=2, verbose_name='\u51bb\u7ed3\u6807\u5fd7')),
                ('area', models.CharField(blank=True, max_length=8, null=True, verbose_name='\u4ed3\u5e93\u533a\u57df')),
                ('mixstore', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='Y', max_length=2, verbose_name='\u662f\u5426\u6df7\u50a8')),
                ('mixbatch', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='Y', max_length=2, verbose_name='\u662f\u5426\u6df7\u6279')),
                ('repeate', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='Y', max_length=2, verbose_name='\u91cd\u590d\u88c5\u6258')),
                ('x', models.IntegerField(default=0, verbose_name='X\u5750\u6807')),
                ('y', models.IntegerField(default=0, verbose_name='Y\u5750\u6807')),
                ('z', models.IntegerField(default=0, verbose_name='Z\u5750\u6807')),
                ('valid_flag', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='Y', max_length=2, verbose_name='\u6709\u6548\u6807\u5fd7')),
                ('standcode', models.CharField(max_length=8, verbose_name='\u6807\u51c6\u4ee3\u7801')),
                ('up', models.IntegerField(default=0, verbose_name='\u4e0a\u5750\u6807')),
                ('left', models.IntegerField(default=0, verbose_name='\u5de6\u5750\u6807')),
                ('length', models.IntegerField(default=0, verbose_name='\u957f\u5ea6')),
                ('width', models.IntegerField(default=0, verbose_name='\u5bbd\u5ea6')),
                ('volume', models.IntegerField(default=0, verbose_name='\u8d27\u7269\u5bb9\u79ef')),
                ('comment', models.CharField(blank=True, max_length=80, null=True, verbose_name='\u5907\u6ce8')),
                ('help_tag', models.CharField(blank=True, max_length=8, null=True, verbose_name='\u52a9\u8bb0\u7b26')),
                ('name', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u4e2d\u6587\u540d\u79f0')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.Customer', verbose_name='\u6240\u5c5e\u5ba2\u6237')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.Warehouse', verbose_name='\u6240\u5c5e\u4ed3\u5e93')),
            ],
            options={
                'verbose_name': '\u5e93\u4f4d',
                'verbose_name_plural': '\u5e93\u4f4d',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(default=1000000, max_length=16, verbose_name='\u5546\u54c1\u7f16\u7801'),
            preserve_default=False,
        ),
    ]
