# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 04:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wms', '0005_auto_20170404_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u8ba2\u5355\u6d41\u6c34(\u7cfb\u7edf\u81ea\u52a8\u751f\u6210)')),
                ('invoice', models.IntegerField(blank=True, null=True, verbose_name='\u53d1\u7968\u53f7')),
                ('pcs', models.IntegerField(blank=True, null=True, verbose_name='\u8ba2\u5355pcs')),
                ('boxes', models.IntegerField(blank=True, null=True, verbose_name='\u5408\u8ba1\u7bb1\u6570')),
                ('order_comment', models.CharField(blank=True, max_length=60, null=True, verbose_name='\u8ba2\u5355\u5907\u6ce8')),
                ('operate_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='\u64cd\u4f5c\u65e5\u671f')),
                ('in_number', models.CharField(blank=True, help_text='\u7559\u7a7a\u7cfb\u7edf\u4f1a\u81ea\u52a8\u751f\u6210', max_length=20, verbose_name='\u5165\u5e93\u7f16\u53f7')),
                ('sender', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u7ed3\u7b97\u5355\u4f4d')),
                ('receiver', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u9001\u8d27\u5355\u4f4d')),
                ('plan_in_time', models.DateField(default=datetime.date.today, verbose_name='\u8ba1\u5212\u5165\u5e93\u65e5\u671f')),
                ('fact_in_time', models.DateField(default=datetime.date.today, verbose_name='\u5b9e\u9645\u5165\u5e93\u65e5\u671f')),
                ('operator', models.CharField(blank=True, max_length=60, null=True, verbose_name='\u5236\u5355\u4eba')),
                ('in_store', models.CharField(choices=[('1', '\u662f'), ('2', '\u5426')], default='2', max_length=4, verbose_name='\u5165\u5e93')),
                ('order_type', models.CharField(choices=[('zc', '\u6b63\u5e38\u5165\u5e93'), ('bl', '\u4e0d\u826f\u54c1\u5165\u5e93'), ('zp', '\u8d60\u54c1\u5165\u5e93'), ('qt', '\u5176\u4ed6')], default='zc', max_length=10, verbose_name='\u8ba2\u5355\u7c7b\u578b')),
                ('order_state', models.CharField(choices=[('1', '\u63a5\u5355'), ('2', '\u5df2\u5165\u5e93')], default='1', max_length=10, verbose_name='\u8ba2\u5355\u72b6\u6001')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.Customer', verbose_name='\u6240\u5c5e\u5ba2\u6237')),
            ],
            options={
                'ordering': ['plan_in_time'],
                'verbose_name': '\u8ba2\u5355(\u5165\u5e93)',
                'verbose_name_plural': '\u8ba2\u5355(\u5165\u5e93)',
            },
        ),
        migrations.CreateModel(
            name='OrderInProductship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderin_pcs', models.IntegerField(default=0, verbose_name='\u5165\u5e93\u6570\u91cf')),
                ('orderin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderIn', verbose_name='\u5165\u5e93\u7f16\u53f7')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.Product', verbose_name='\u5546\u54c1\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u5165\u5e93\u8ba2\u5355-\u5546\u54c1\u660e\u7ec6',
                'verbose_name_plural': '\u5165\u5e93\u8ba2\u5355-\u5546\u54c1\u660e\u7ec6',
            },
        ),
        migrations.CreateModel(
            name='OrderOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u8ba2\u5355\u6d41\u6c34(\u7cfb\u7edf\u81ea\u52a8\u751f\u6210)')),
                ('invoice', models.IntegerField(blank=True, null=True, verbose_name='\u53d1\u7968\u53f7')),
                ('pcs', models.IntegerField(blank=True, null=True, verbose_name='\u8ba2\u5355pcs')),
                ('boxes', models.IntegerField(blank=True, null=True, verbose_name='\u5408\u8ba1\u7bb1\u6570')),
                ('order_comment', models.CharField(blank=True, max_length=60, null=True, verbose_name='\u8ba2\u5355\u5907\u6ce8')),
                ('operate_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='\u64cd\u4f5c\u65e5\u671f')),
                ('out_number', models.CharField(blank=True, help_text='\u7559\u7a7a\u7cfb\u7edf\u4f1a\u81ea\u52a8\u751f\u6210', max_length=20, unique=True, verbose_name='\u51fa\u5e93\u7f16\u53f7')),
                ('fact_out_time', models.DateField(default=datetime.date.today, verbose_name='\u51fa\u5e93\u65e5\u671f')),
                ('receiver', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u6536\u8d27\u4eba')),
                ('receiver_addr', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u9001\u8d27\u5730\u5740')),
                ('receiver_phone', models.IntegerField(blank=True, null=True, verbose_name='\u6536\u8d27\u4eba\u7535\u8bdd')),
                ('operator', models.CharField(blank=True, max_length=60, null=True, verbose_name='\u51fa\u5e93\u4eba')),
                ('out_store', models.CharField(choices=[('1', '\u662f'), ('2', '\u5426')], default='2', max_length=4, verbose_name='\u51fa\u5e93')),
                ('order_type', models.CharField(choices=[('zc', '\u6b63\u5e38\u51fa\u5e93'), ('bl', '\u4e0d\u826f\u54c1\u51fa\u5e93'), ('zp', '\u8d60\u54c1\u51fa\u5e93'), ('qt', '\u5176\u4ed6')], default='zc', max_length=10, verbose_name='\u8ba2\u5355\u7c7b\u578b')),
                ('order_state', models.CharField(choices=[('1', '\u63a5\u5355'), ('2', '\u5df2\u51fa\u5e93')], default='1', max_length=10, verbose_name='\u8ba2\u5355\u72b6\u6001')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.Customer', verbose_name='\u6240\u5c5e\u5ba2\u6237')),
            ],
            options={
                'ordering': ['fact_out_time'],
                'verbose_name': '\u8ba2\u5355(\u51fa\u5e93)',
                'verbose_name_plural': '\u8ba2\u5355(\u51fa\u5e93)',
            },
        ),
        migrations.CreateModel(
            name='OrderOutProductship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderout_pcs', models.IntegerField(default=0, verbose_name='\u51fa\u5e93\u6570\u91cf')),
                ('orderout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderOut', verbose_name='\u51fa\u5e93\u7f16\u53f7')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.Product', verbose_name='\u5546\u54c1\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u51fa\u5e93\u8ba2\u5355-\u5546\u54c1\u660e\u7ec6',
                'verbose_name_plural': '\u51fa\u5e93\u8ba2\u5355-\u5546\u54c1\u660e\u7ec6',
            },
        ),
        migrations.AddField(
            model_name='orderout',
            name='product',
            field=models.ManyToManyField(through='order.OrderOutProductship', to='wms.Product', verbose_name='\u5546\u54c1\u540d\u79f0'),
        ),
        migrations.AddField(
            model_name='orderout',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.Warehouse', verbose_name='\u64cd\u4f5c\u4ed3\u5e93'),
        ),
        migrations.AddField(
            model_name='orderin',
            name='product',
            field=models.ManyToManyField(through='order.OrderInProductship', to='wms.Product', verbose_name='\u5546\u54c1\u540d\u79f0'),
        ),
        migrations.AddField(
            model_name='orderin',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.Warehouse', verbose_name='\u64cd\u4f5c\u4ed3\u5e93'),
        ),
    ]
