# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderin',
            name='in_store',
            field=models.CharField(choices=[('y', '\u5df2\u5b8c\u6210'), ('n', '\u672a\u5b8c\u6210')], default='2', max_length=4, verbose_name='\u5165\u5e93'),
        ),
        migrations.AlterField(
            model_name='orderout',
            name='out_store',
            field=models.CharField(choices=[('1', '\u5df2\u5b8c\u6210'), ('2', '\u672a\u5b8c\u6210')], default='2', max_length=4, verbose_name='\u51fa\u5e93'),
        ),
    ]
